### ISSUE TITLE
"CCNG Catalog Manager:(v2) Error decoding reply from gateway" when having a lot of service instances

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/vcap-services-base#21]
When trying to start a service gateway which is connected to a Cloud Foundry with a lot of service instances we end up in a restart loop.
This happens because during the [multiple page fetch](https://github.com/cloudfoundry/vcap-services-base/blob/master/lib/base/cloud_controller_services.rb#L59-L70) sometimes an http call fails and as a result the whole gateway gets restarted.

**Comment by shalako** [comment]
Hello Ruben,

As vcap-services-base is deprecated, we're not adding features to it. Is it an option for you to update your brokers to the v2 broker API?

**Comment by rkoster** [comment]
@shalako I know this repository has been deprecated. But this repository is still a dependency of [cf-services-contrib-release](https://github.com/cloudfoundry-community/cf-services-contrib-release). Which is still being used by the community. Would it be an option to move vcap-services-base into the [cloudfoundry-community](https://github.com/cloudfoundry-community/) organisation as well?

**Comment by shalako** [comment]
Hi Ruben, nothing would please me more than to move vcap-services-base into cloudfoundry-community. I'll have to check if we need to go through the foundation to get that approved.
